[versions]
jdk = "11"
checkstyle = "8.45.1"

[plugins]
javafx = "org.openjfx.javafxplugin:0.1.0"

[libraries]
# lint
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
rulebook-checkstyle = "com.hendraanggrian.rulebook:rulebook-checkstyle:0.3"
# test
truth = "com.google.truth:truth:1.1.5"
